### ISSUE TITLE
Collector starts connects then dies

### ISSUE THREAD

**Issue by philliproso** [logicmonitor/docker_lm_collector#2]
The collector starts adds an entry to logicmonitor then dies.  This is from docker logs. Any idea whats going on. 

DEBUG:root:Instantiating Collector object
DEBUG:root:Instantiating LogicMonitor object
DEBUG:root:Running Collector._get...
DEBUG:root:Running LogicMonitor.get_collectors...
DEBUG:root:Making RPC call to 'getAgents'
DEBUG:root:Running LogicMonitor.rpc
DEBUG:root:RPC call succeeded
DEBUG:root:Collectors returned
DEBUG:root:Installing collector.
DEBUG:root:Running Collector.create...
DEBUG:root:Running Collector._create...
DEBUG:root:Platform is Linux
DEBUG:root:Running Collector._get...
DEBUG:root:Running LogicMonitor.get_collectors...
DEBUG:root:Making RPC call to 'getAgents'
DEBUG:root:Running LogicMonitor.rpc
DEBUG:root:RPC call succeeded
DEBUG:root:Collectors returned
DEBUG:root:System changed
DEBUG:root:Making RPC call to 'addAgent'
DEBUG:root:Running LogicMonitor.rpc
DEBUG:root:RPC call succeeded
DEBUG:root:Running Collector.get_installer_binary...
DEBUG:root:64 bit system
DEBUG:root:Platform is Linux
DEBUG:root:Agent ID is 11
DEBUG:root:Looking for existing installer at /usr/local/logicmonitor/logicmonitorsetup11_64.bin
DEBUG:root:No previous installer found
DEBUG:root:System changed
DEBUG:root:Downloading installer file
DEBUG:root:Running LogicMonitor.do...
DEBUG:root:Attempting to open URL: https://xxxxx.logicmonitor.com/santaba/do/logicmonitorsetup?arch=64&id=11&

**Comment by woz5999** [comment]
Hi Phillip. Sorry for the late response. Our support team has forwarded me another error log you provided: 10-05 11:15:56.128 UTC] [NOTICE] [ERROR] [main:::] [AgentStatus._checkPeerStatus:185] CAUSE=Encounter exception, ACTION=Try again, CONTEXT=i=1, EXCEPTION=Encounter exception - Connection refused
[10-05 11:13:51.292 UTC] [MSG] [WARN] [main:::] [PeerSocketChannel.<init>:57] Encounter exception when connect to peer, CONTEXT=port=7212, EXCEPTION=Connection refused
java.net.ConnectException: Connection refused
    at sun.nio.ch.Net.connect0(Native Method)
    at sun.nio.ch.Net.connect(Net.java:454)
    at sun.nio.ch.Net.connect(Net.java:446)
    at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
    at com.santaba.agent.agentmonitor.PeerSocketChannel.<init>(PeerSocketChannel.java:44)
    at com.santaba.agent.agentmonitor.AgentStatus._checkPeerStatus(AgentStatus.java:140)
    at com.santaba.agent.agentmonitor.AgentStatus.checkAgent2(AgentStatus.java:99)
    at com.santaba.agent.agentmonitor.AgentStatus.checkAgentRunning(AgentStatus.java:504)
    at com.santaba.agent.watchdog.WatchdogMain.main(WatchdogMain.java:377)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:126)
    at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:66)

To me, this indicates that you've overcome the issue pasted above and looks like the collector has been installed but is failing to start properly. Let me know if I'm mistaken here, otherwise, I suspect that this new error is network related. It could perhaps be an issue with docker networking config or perhaps a firewall. Is there any additional information you can provide about your environment in this regard? You can contact me at jeff.wozniak at logicmonitor.com

**Comment by woz5999** [comment]
@philliproso I've pushed some updates to the container that may help with the issues you were experiencing. Since we haven't heard from you in awhile, I'm going to close this issue. If you come across something new in the future, please feel free to open a new issue.
