### ISSUE TITLE
Collector Upstart "Collector Deleted"

### ISSUE THREAD

**Issue by shaunofneuron** [logicmonitor/docker_lm_collector#8]
This issue has been going on for a few months now. Seeing issues where newly provisioned hosts starting the lm_collector would be running without an active collector running inside the container. The issue goes away with a restart of the container but looking for a more steady solution.  Part of our upstart routine starts the container and sets as a failover for other collectors in the same collector group, this is a no-op if the collector doesn't exist.

```[06-22 15:22:55.256 UTC] [MSG] [DEBUG] [main::controller:main] [Settings.merge:825] Update settings with property, CONTEXT=file=/usr/local/logicmonitor/agent/conf/agent.conf.local
[06-22 15:22:55.257 UTC] [MSG] [ERROR] [main::controller:main] [Settings.merge:830] Merge settings encounter exception, CONTEXT=conf=/usr/local/logicmonitor/agent/conf/agent.conf.local, EXCEPTION=/usr/local/logicmonitor/agent/conf/agent.conf.local (No such file or directory)
java.io.FileNotFoundException: /usr/local/logicmonitor/agent/conf/agent.conf.local (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.santaba.agent.util.Settings.merge(Settings.java:826)
	at com.santaba.agent.controller.Controller2._initConfiguration(Controller2.java:293)
	at com.santaba.agent.controller.Controller2.run(Controller2.java:1135)
	at com.santaba.agent.Main.main(Main.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:124)
	at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:64)

[06-22 15:22:55.257 UTC] [MSG] [INFO] [main::controller:main] [Controller2._initConfiguration:300] Initialize default logging level, CONTEXT=logLevel=info
[06-22 15:22:55.258 UTC] [MSG] [INFO] [main::controller:main] [Controller2._initConfiguration:316] Starting persistent cache, CONTEXT=
DEBUG:root:Service logicmonitor-watchdog is not running
DEBUG:root:System changed
DEBUG:root:Starting logicmonitor-watchdog service
DEBUG:root:Performing start on service logicmonitor-watchdog
DEBUG:root:Getting service logicmonitor-watchdog control type
DEBUG:root:Service control is via init.d
[06-22 15:22:55.883 UTC] [MSG] [INFO] [main::controller:main] [Settings.getCSProxyAddresses:1090] Found CS proxy address, CONTEXT=index=0, address=52.52.63.47
[06-22 15:22:55.883 UTC] [MSG] [INFO] [main::controller:main] [Settings.getCSProxyAddresses:1090] Found CS proxy address, CONTEXT=index=1, address=52.202.255.101
[06-22 15:22:55.883 UTC] [MSG] [INFO] [main::controller:main] [Settings.getCSProxyAddresses:1090] Found CS proxy address, CONTEXT=index=2, address=54.194.232.54
[06-22 15:22:55.883 UTC] [MSG] [INFO] [main::controller:main] [Settings.getCSProxyAddresses:1090] Found CS proxy address, CONTEXT=index=3, address=54.209.7.170
[06-22 15:22:55.889 UTC] [INFO] [1] [default] [controller] [DNSResolver.initialize:70] Using system default DNS resolving (provider=system)
[06-22 15:22:55.917 UTC] [MSG] [INFO] [main::controller:main] [HttpClient.<init>:124] Try enforce strong ciphers, CONTEXT=
[06-22 15:22:56.106 UTC] [INFO] [1] [default] [controller] [AgentID.<init>:60] Generated ID prefix - 8a03d01a-587a-4837-8fac-0250acf8c0cf
[06-22 15:22:56.107 UTC] [INFO] [1] [default] [controller] [AgentID.<init>:73] Using cached ID prefix - adfd180f-8b4b-4043-a2bf-d67f0dcdf362
[06-22 15:22:56.108 UTC] [INFO] [1] [default] [controller] [Controller2._initHttpService:486] Agent starting with ID - adfd180f-8b4b-4043-a2bf-d67f0dcdf362sbagent
[06-22 15:22:56.104 UTC] [MSG] [INFO] [main::controller:main] [HttpClient.<init>:134] Try trust all certificates, CONTEXT=
[06-22 15:22:56.451 UTC] [MSG] [INFO] [main::controller:main] [SSLUtilities.testSSLConnection:196] Handshake started ... Check host names ..., CONTEXT=host=*****.logicmonitor.com, port=443
[06-22 15:22:56.452 UTC] [MSG] [INFO] [main::controller:main] [SSLUtilities.testSSLConnection:202] Server is trusted, CONTEXT=
[06-22 15:22:56.461 UTC] [MSG] [INFO] [main::controller:main] [Controller2._initConfiguration:354] SANTABA SERVER certificates OK, CONTEXT=
[06-22 15:22:56.461 UTC] [MSG] [INFO] [main::controller:main] [Controller2._initConfiguration:399] Initialize configuration, CONTEXT=sbAgentRoot=/usr/local/logicmonitor/agent, platform=linux, agentId=126, debugDisabled=false
[06-22 15:22:56.687 UTC] [MSG] [WARN] [main::controller:main] [Controller2._initConfiguration:462] Unexpected status encountered from server. Will retry., CONTEXT=retry=30s, statusCode= 408, errMsg=Collector Deleted
gobler terminated OUTPUT 55
gobler terminated ERROR 55
```

The "Collector Deleted" error message is probably most relevant but I cant see behind the veil to know what's actually going on. Eventually the "gobler terminated" happens but not 30s after the retry, in fact there is no additional output after the "Will retry" so my guess is that it doesn't actually attempt 30s after that error appears.  Any insight definitely appreciated as I have been sitting on this issue for a while now.

**Comment by woz5999** [comment]
Can you provide the image tag and hash you're experiencing this with?
Can also provide a more detailed sequence of events for how you're provisioning hosts and running the container? Maybe also an example docker run command or similar specification of how you're configuring the container.

At first blush, the error message "Collector Deleted" indicates that a collector is attempting to call home with a collector ID that is no longer valid (never exists, was deleted, etc) in your LogicMonitor portal. When a collector encounters this message, it is configured to self-destruct in order to limit the likelihood that an old or misconfigured collector will leak data.

I would guess that something in your sequence of events is resulting in container collectors being created or resurrected with invalid IDs.

**Comment by shaunofneuron** [comment]
Thanks for the input @woz5999 
```
"sha256:8b6cd464b4d68b0c5a5fb9830f9c4a398d2dc8883237a78ee896d9e6f191344f"
"Image": "logicmonitor/lm_collector:latest"
```

1. Create collector container (**without** collector ID env var)
2. Store container id
3. Pass container id to api call routine (custom python library via ansible)
4. Call routine creates collector device group if it doesn't exist (generally always does)
5. Call routine determines if collector is in the collector group, if it is not it will move it
6. Call routine links all collectors in group to its neighbor as failover, last collector links to first

The only issue I've had with this routine is in step 5 which gets picked up on the next run ~20 minutes later. The collector is not started up so it hasn't registered itself yet with LM, when the routine tries to find it in the default collector group it fails, but as I said it works on the second run so long as the collector has started.

The ansible play that runs the container doesn't ever attempt a restart of the docker container so I know that the container ID will persist through ansible runs (~20 minutes). Again I am leaving the initial collector registration up to the container.

The only thing I can see from the collector event log is this:

```
2017-06-19 16:03:58 MDT	Agent is restarted
2017-06-19 16:03:47 MDT	Credential is rotated. Agent will restart.
2017-06-18 16:03:55 MDT	Agent is restarted
2017-06-18 16:03:44 MDT	Credential is rotated. Agent will restart.
2017-06-17 16:03:52 MDT	Agent is restarted
2017-06-17 16:03:41 MDT	Credential is rotated. Agent will restart.
2017-06-16 16:03:39 MDT	Agent is restarted
```

Here's the ansible (compose) yml:
```
- name: logicmonitor collector docker container
  docker_container:
    name: logicmonitor
    docker_api_version: 1.23
    image: "logicmonitor/lm_collector:latest"
    state: started
    restart_policy: unless-stopped
    env:
      cleanup: "true"
      company: ""
      username: ""
      password: ""
      description: "{{ ansible_hostname }}"
  when: collector
```

Curious as to what you think is going on, I might try this without specifying the cleanup property.

**Comment by woz5999** [comment]
Hi @shaunofneuron 

I just wanted to let you know that I haven't forgotten you; just got back from vacation and will taking a look in the next few days.

**Comment by woz5999** [comment]
@shaunofneuron We've just released a beta version of an updated docker collector that includes a number of additional features and uses our REST API. I think that some of the features in this collector may help to address some of the issues you're encountering. For example, the new version includes:

- The ability to specify a collector group to join at start up
- The ability to locate an existing collector via collector description in addition to collector id
- Improvements detecting collector failures and exiting the collector in the event of a failure

A pull request for the updates exists here: https://github.com/logicmonitor/docker_lm_collector/pull/12

The new image and documentation can be found here: https://hub.docker.com/r/logicmonitor/collector/ [ tag = beta ]

Let me know if this helps and if there's anything else I can do

**Comment by shaunofneuron** [comment]
Thanks @woz5999 - appreciate the info. I was caught red-handed when the repo changed names, will there be a more formal way of notifying consumers of these sort of changes?

**Comment by woz5999** [comment]
the docker collector is still a beta offering, so there isn't currently a well-defined notification mechanism at this point.

when you say red-handed, I hope you don't mean that the name change affected your running environment. if that's the case, please let me know because the change should have been structured in such a way as to not affect existing users.
